server:
  port: 6001
spring:
  main:
    web-application-type: reactive

logging:
  level:
    com.netflix: debug
    #org.springframework: DEBUG




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true
    routes:
      enabled: true