spring:
  profiles:
    active: dev

knife4j:
  production: false
  enable: true
  basic:
    enable: false
    username: admin
    password: admin

nacos:
  server: 101.43.63.132:8848
  username: dev
  password: dev
  namespace: 76f1596d-8d58-404c-adff-30494b5cc784
